---
name: node-exporter

instance_groups:
  - name: node-exporter
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: node_exporter
        release: node-exporter

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

releases:
- name: node-exporter
  version: 3.0.1
  url: https://github.com/bosh-prometheus/node-exporter-boshrelease/releases/download/v3.0.1/node-exporter-3.0.1.tgz
  sha1: e2a70d0574d53a5b4f72e37a2fca8a5d39b022ac
