---
name: node-exporter

instance_groups:
  - name: node-exporter
    azs:
      - z1
    instances: 1
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: node_exporter
        release: node-exporter

update:
  canaries: 0
  max_in_flight: 1
  serial: true
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-100000
  update_watch_time: 1000-100000
  serial: false

stemcells:
  - alias: default
    os: ubuntu-trusty
    version: latest

releases:
- name: node-exporter
  version: 2.0.1
  url: https://github.com/cloudfoundry-community/node-exporter-boshrelease/releases/download/v2.0.1/node-exporter-2.0.1.tgz
  sha1: d8f78005741291a0500754accb514b52a25db4af
