meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 32
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: node_exporter
    templates:
      - name: node_exporter
        release: node-exporter
    instances: 1
    resource_pool: small
    networks: (( param "please set node_exporter networks" ))

networks: (( param "please set networks" ))

properties: {}
