---
meta:
  name:    node-exporter
  target:  sw
  url:     https://ci.starkandwayne.com

  aws:
    bucket:      node-exporter-boshrelease
    region_name: us-east-1
    access_key:  (( vault "secret/aws/cfcommunity:access" ))
    secret_key:  (( vault "secret/aws/cfcommunity:secret" ))

  docker:
    username:     (( vault "secret/pipelines/node-exporter-boshrelease/docker:username" ))
    password:     (( vault "secret/pipelines/node-exporter-boshrelease/docker:password" ))
    organization: boshprometheus

  git:
    email: (( vault "secret/pipelines/node-exporter-boshrelease/github:email" ))
    name:  (( vault "secret/pipelines/node-exporter-boshrelease/github:name" ))

  github:
    owner:        bosh-prometheus
    branch:       master
    private_key:  (( vault "secret/pipelines/node-exporter-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/node-exporter-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/node-exporter-boshrelease/slack:webhook" ))
    channel: '#prometheus'

groups:
  - name: blobs
    jobs:
      - node_exporter

jobs:
  - name: node_exporter
    public: true
    serial: true
    plan:
      - aggregate:
        - get: node_exporter
          trigger: true
          params:
            globs:
              - node_exporter-*.linux-amd64.tar.gz

      - put: notify
        params:
          channel:   (( grab meta.slack.channel ))
          username:  (( grab meta.slack.username ))
          icon_url:  (( grab meta.slack.icon ))
          text:     '$BUILD_PIPELINE_NAME: New node-exporter version $TEXT_FILE_CONTENT has been detected'
          text_file: node_exporter/version

resources:
  - name: node_exporter
    type: github-release
    source:
      user:         prometheus
      repository:   node_exporter
      access_token: (( grab meta.github.access_token ))
      check_every:  30m
