---
meta:
  name:    node-exporter
  target:  sw
  url:     https://ci.starkandwayne.com
  initial_version: 1.0.0

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   node-exporter-boshrelease
    private_key:  (( vault "secret/pipelines/node-exporter-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/node-exporter-boshrelease/github:token" ))

  bosh-lite:
    target: https://10.58.111.44:25555
    deployment: node-exporter-warden

  slack:
    webhook: (( vault "secret/pipelines/node-exporter-boshrelease/slack:webhook" ))
    channel: '#botspam'
